name: Build Docker Image excel-processor

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: excel-processor:${{ github.event.release.tag_name }}

      - name: Save image
        run: |
          docker save excel-processor:${{ github.event.release.tag_name }} | gzip > excel-processor-${{ github.event.release.tag_name }}.tar.gz

      - name: Upload to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./excel-processor-${{ github.event.release.tag_name }}.tar.gz
          asset_name: excel-processor-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip
